@BASE_URL = http://localhost:3000

###
GET {{BASE_URL}}/

###
POST {{BASE_URL}}/userRegister
Content-Type: application/json

{
    "name" : "sadsadas",
    "email" : "sadasd",
    "password" : "wsdsadsad",
    "username" : "sadasdasd",
    "surname" : "sadasd"
}
###
POST {{BASE_URL}}/userLogin
Content-Type: application/json

{
    "username" : "deneme",
    "password" : "deneme123"
}